name: K6 load test
on: [push]
jobs:
  build: K6 load test
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run K6 load test
      uses: grafana/k6-action@v0.2.0
      with:
       filename: modulo5_conteudo_adicional/aula31.js