name: K6 load test
on: [push]
permissions:
  contents: write
jobs:
  build:
    name: Run K6 load test
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run K6 load test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: script_action.js

      - run: ls & mkdir reports & mv index.html reports/index.html

      - name: K6 HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: k6-html-report
          path: reports

      - name: Deploy K6 JSON report artifact
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          public_branch: gh-pages
          destination_dir: reports